# lovelace_gen

#===========================
#=== Controller WiFi Signal
#===========================
type: custom:button-card
entity: {{ entity }}
name: {{ name }}
icon: "[[[ return (entity === undefined || entity.state == 'unavailable') ? 'mdi:wifi-off' : 'mdi:wifi'; ]]]"
show_state: true
state_display: >
  [[[
    var statestr = (entity === undefined || entity.state === undefined) ? 'undefined' : entity.state;
    var unit_om = (statestr != 'undefined' && entity.attributes.unit_of_measurement) ? entity.attributes.unit_of_measurement : '';
    return statestr + ' ' + unit_om;
  ]]]
size: 30%
styles:
  grid:
    - grid-template-areas: '"i n s"'
    - grid-template-columns: 15% auto 20%
    - grid-template-rows: min-content
  card:
    - font-family: "[[[ return states['input_text.irrigation_ui_font_family'].state ]]]"
    - font-size: 15px
    - padding: 0em 0em 0.5em 0em
    - background: none
    - box-shadow: none
  name: 
    - justify-self: start
state:
  - value: 'unavailable'
    styles:
      icon:
        - color: var(--accent-color)
        - animation: blink 2s ease infinite
      state:
        - color: var(--accent-color)
        - animation: blink 2s ease infinite
tap_action:
  action: call-service
  service: browser_mod.popup
  service_data:
    title: Irrigation Controller
    card:
      type: vertical-stack
      cards:
        - type: markdown
          content: Enter the name of the sensor for your irrigation controller WiFi signal strength.


                  Leave blank to reset to default.
          style: >
            ha-card {
              box-shadow: none;
              padding: 0em 0em 0em 1em;
              background: var(--paper-dialog-background-color);
              margin: 0em;
            }
            p {
              font-size: 18px;
            }
        - type: entities
          entities:
            - entity: input_text.irrigation_external_sensor_controller_wifi
              name: Sensor Name
            - type: section
          style: >
            ha-card {
              box-shadow: none;
              border-radius: 0em 0em 1em 1em;
              background: var(--paper-dialog-background-color);
            }
        - type: markdown
          content: You can disable the switches to prevent irrigation while testing.
          style: >
            ha-card {
              box-shadow: none;
              padding: 0em 0em 0em 1em;
              background: var(--paper-dialog-background-color);
              margin: 0em;
            }
            p {
              font-size: 18px;
            }
        - type: entities
          entities:
            - entity: input_boolean.irrigation_disable_switches
          style: >
            ha-card {
              box-shadow: none;
              border-radius: 0em 0em 1em 1em;
              background: var(--paper-dialog-background-color);
            }
    deviceID:
      - this
    style:
      font-family: >
        [[[
          return states['input_text.irrigation_ui_font_family'].state
        ]]]
      box-shadow: 0em 0em 0.5em
      border-radius: 1em
      overflow: hidden
      opacity: 0.9
