# lovelace_gen

#==================
#=== SETTINGS LINE
#==================
type: custom:button-card
entity: {{ entity }}
show_state: true
name: {{ name }}
icon: {{ icon }}
show_label: true
label: {{ label }}
size: 30%
tap_action:
  action: call-service
  service: browser_mod.popup
  service_data:
    title: " &nbsp \U00002139 &nbsp &nbsp WEATHER ADJUSTMENTS"
    card:
      type: markdown
      content: >
        ### Rain multiplier
        
        This multiplier will decrease watering time proportionally
        based on the difference between the rainfall threshold and the amount of
        rain over the last few days.

        
        If the threshold is reached then it will stop it altogether.


        ---


        ### Temperature multiplier

        This multiplier will increase or decrease watering time proportionally
        based on the difference between the temperature threshold and the 
        average high temperature over the last few days.


        It is calculated as High Temperature divided by Baseline Temperature.


        For example, if the baseline temperature is set to 25 degrees and the
        average temperature has been 30 degrees the adjustent will be plus 20%.


        Likewise if the average temperature has only been 20 degrees the
        adjustment will be minus 20%.
      style: >
        ha-card {
          border-radius: 0em 0em 1em 1em
        }
    deviceID:
      - this
    style:
      font-family: >
        [[[
          return states['input_text.irrigation_ui_font_family'].state
        ]]]
      box-shadow: 0em 0em 0.5em
      border-radius: 1em
      overflow: hidden
      opacity: 0.9
styles:
  grid:
    - grid-template-areas: >
        [[[
          if ('{{ label }}' == '')
            return '"i n s"  "i n s"';
          else
            return '"i n s"  "i l s"';
        ]]]
    - grid-template-columns: 15% auto 15%
    - grid-template-rows: min-content min-content
  card:
    - font-family: "[[[ return states['input_text.irrigation_ui_font_family'].state ]]]"
    - font-size: 15px
    - padding: 0em 0em 0.5em 0em
    - background: none
    - box-shadow: none
  name: 
    - justify-self: start
  label:
    - justify-self: start
    - color: var(--secondary-text-color)
